import { z } from "zod";

export const workspaceOptionKinds = [
  "currency",
  "destination-country",
  "address-book",
  "supplier-product-type",
] as const;
export type WorkspaceOptionKind = (typeof workspaceOptionKinds)[number];

export const workspaceOptionSchema = z.object({
  id: z.string().trim().min(1),
  kind: z.enum(workspaceOptionKinds),
  code: z.string().trim().min(1).max(254),
  name: z.string().trim().min(1).max(120),
  symbol: z.string().trim().max(12).nullable(),
  isFavorite: z.boolean().optional().default(false),
  sortIndex: z.number().int().min(0),
});

export const workspaceOptionListSchema = z.array(workspaceOptionSchema);
export type WorkspaceOption = z.infer<typeof workspaceOptionSchema>;

export const MAX_GENERIC_NODE_IMAGES = 50;

export const genericNodeImageSchema = z.object({
  id: z.string().trim().min(1),
  name: z.string().trim().min(1).max(255),
  url: z.string().trim().min(1),
  storagePath: z.string().trim().min(1).nullable(),
});

export const genericNodeImageListSchema = z
  .array(genericNodeImageSchema)
  .min(1, "Upload at least one image.")
  .max(MAX_GENERIC_NODE_IMAGES, `Upload no more than ${MAX_GENERIC_NODE_IMAGES} images.`);

export const genericNodeDefinitionInputSchema = z.object({
  name: z.string().trim().min(1).max(80),
  images: genericNodeImageListSchema,
});

const genericNodeDefinitionRecordSchema = z
  .object({
    id: z.string().trim().min(1),
    name: z.string().trim().min(1).max(80),
    images: genericNodeImageListSchema.optional(),
    // Accepted while reading records saved before multi-image definitions.
    imageUrl: z.string().trim().min(1).optional(),
    storagePath: z.string().trim().min(1).nullable().optional(),
    sortIndex: z.number().int().min(0),
    // PostgREST serializes timestamptz with a numeric offset (e.g. "+00:00"),
    // while the local store uses an ISO "Z" suffix. Accept both.
    createdAt: z.string().datetime({ offset: true }),
    updatedAt: z.string().datetime({ offset: true }),
  })
  .superRefine((value, context) => {
    if (!value.images?.length && !value.imageUrl) {
      context.addIssue({
        code: "custom",
        path: ["images"],
        message: "Upload at least one image.",
      });
    }
  })
  .transform(({ imageUrl, storagePath, ...value }) => ({
    ...value,
    images: value.images ?? [
      {
        id: `${value.id}:image:0`,
        name: "Image 1",
        url: imageUrl ?? "",
        storagePath: storagePath ?? null,
      },
    ],
  }));

/** Reads both current multi-image records and legacy single-image records. */
export const genericNodeDefinitionSchema = genericNodeDefinitionRecordSchema;

export type GenericNodeDefinition = z.infer<typeof genericNodeDefinitionSchema>;
export type GenericNodeDefinitionInput = z.infer<typeof genericNodeDefinitionInputSchema>;
export type GenericNodeImage = z.infer<typeof genericNodeImageSchema>;

interface IntlWithSupportedValues {
  supportedValuesOf?: (key: "currency") => string[];
}

const FALLBACK_CURRENCY_CODES = [
  "AED",
  "AFN",
  "ALL",
  "AMD",
  "ANG",
  "AOA",
  "ARS",
  "AUD",
  "AWG",
  "AZN",
  "BAM",
  "BBD",
  "BDT",
  "BGN",
  "BHD",
  "BIF",
  "BMD",
  "BND",
  "BOB",
  "BOV",
  "BRL",
  "BSD",
  "BTN",
  "BWP",
  "BYN",
  "BZD",
  "CAD",
  "CDF",
  "CHE",
  "CHF",
  "CHW",
  "CLF",
  "CLP",
  "CNY",
  "COP",
  "COU",
  "CRC",
  "CUC",
  "CUP",
  "CVE",
  "CZK",
  "DJF",
  "DKK",
  "DOP",
  "DZD",
  "EGP",
  "ERN",
  "ETB",
  "EUR",
  "FJD",
  "FKP",
  "GBP",
  "GEL",
  "GHS",
  "GIP",
  "GMD",
  "GNF",
  "GTQ",
  "GYD",
  "HKD",
  "HNL",
  "HTG",
  "HUF",
  "IDR",
  "ILS",
  "INR",
  "IQD",
  "IRR",
  "ISK",
  "JMD",
  "JOD",
  "JPY",
  "KES",
  "KGS",
  "KHR",
  "KMF",
  "KPW",
  "KRW",
  "KWD",
  "KYD",
  "KZT",
  "LAK",
  "LBP",
  "LKR",
  "LRD",
  "LSL",
  "LYD",
  "MAD",
  "MDL",
  "MGA",
  "MKD",
  "MMK",
  "MNT",
  "MOP",
  "MRU",
  "MUR",
  "MVR",
  "MWK",
  "MXN",
  "MXV",
  "MYR",
  "MZN",
  "NAD",
  "NGN",
  "NIO",
  "NOK",
  "NPR",
  "NZD",
  "OMR",
  "PAB",
  "PEN",
  "PGK",
  "PHP",
  "PKR",
  "PLN",
  "PYG",
  "QAR",
  "RON",
  "RSD",
  "RUB",
  "RWF",
  "SAR",
  "SBD",
  "SCR",
  "SDG",
  "SEK",
  "SGD",
  "SHP",
  "SLE",
  "SLL",
  "SOS",
  "SRD",
  "SSP",
  "STN",
  "SVC",
  "SYP",
  "SZL",
  "THB",
  "TJS",
  "TMT",
  "TND",
  "TOP",
  "TRY",
  "TTD",
  "TWD",
  "TZS",
  "UAH",
  "UGX",
  "USD",
  "USN",
  "UYI",
  "UYU",
  "UYW",
  "UZS",
  "VED",
  "VES",
  "VND",
  "VUV",
  "WST",
  "XAF",
  "XAG",
  "XAU",
  "XBA",
  "XBB",
  "XBC",
  "XBD",
  "XCD",
  "XDR",
  "XOF",
  "XPD",
  "XPF",
  "XPT",
  "XSU",
  "XTS",
  "XUA",
  "XXX",
  "YER",
  "ZAR",
  "ZMW",
  "ZWG",
] as const;

const COUNTRY_CODES = [
  "AD",
  "AE",
  "AF",
  "AG",
  "AI",
  "AL",
  "AM",
  "AO",
  "AQ",
  "AR",
  "AS",
  "AT",
  "AU",
  "AW",
  "AX",
  "AZ",
  "BA",
  "BB",
  "BD",
  "BE",
  "BF",
  "BG",
  "BH",
  "BI",
  "BJ",
  "BL",
  "BM",
  "BN",
  "BO",
  "BQ",
  "BR",
  "BS",
  "BT",
  "BV",
  "BW",
  "BY",
  "BZ",
  "CA",
  "CC",
  "CD",
  "CF",
  "CG",
  "CH",
  "CI",
  "CK",
  "CL",
  "CM",
  "CN",
  "CO",
  "CR",
  "CU",
  "CV",
  "CW",
  "CX",
  "CY",
  "CZ",
  "DE",
  "DJ",
  "DK",
  "DM",
  "DO",
  "DZ",
  "EC",
  "EE",
  "EG",
  "EH",
  "ER",
  "ES",
  "ET",
  "FI",
  "FJ",
  "FK",
  "FM",
  "FO",
  "FR",
  "GA",
  "GB",
  "GD",
  "GE",
  "GF",
  "GG",
  "GH",
  "GI",
  "GL",
  "GM",
  "GN",
  "GP",
  "GQ",
  "GR",
  "GS",
  "GT",
  "GU",
  "GW",
  "GY",
  "HK",
  "HM",
  "HN",
  "HR",
  "HT",
  "HU",
  "ID",
  "IE",
  "IL",
  "IM",
  "IN",
  "IO",
  "IQ",
  "IR",
  "IS",
  "IT",
  "JE",
  "JM",
  "JO",
  "JP",
  "KE",
  "KG",
  "KH",
  "KI",
  "KM",
  "KN",
  "KP",
  "KR",
  "KW",
  "KY",
  "KZ",
  "LA",
  "LB",
  "LC",
  "LI",
  "LK",
  "LR",
  "LS",
  "LT",
  "LU",
  "LV",
  "LY",
  "MA",
  "MC",
  "MD",
  "ME",
  "MF",
  "MG",
  "MH",
  "MK",
  "ML",
  "MM",
  "MN",
  "MO",
  "MP",
  "MQ",
  "MR",
  "MS",
  "MT",
  "MU",
  "MV",
  "MW",
  "MX",
  "MY",
  "MZ",
  "NA",
  "NC",
  "NE",
  "NF",
  "NG",
  "NI",
  "NL",
  "NO",
  "NP",
  "NR",
  "NU",
  "NZ",
  "OM",
  "PA",
  "PE",
  "PF",
  "PG",
  "PH",
  "PK",
  "PL",
  "PM",
  "PN",
  "PR",
  "PS",
  "PT",
  "PW",
  "PY",
  "QA",
  "RE",
  "RO",
  "RS",
  "RU",
  "RW",
  "SA",
  "SB",
  "SC",
  "SD",
  "SE",
  "SG",
  "SH",
  "SI",
  "SJ",
  "SK",
  "SL",
  "SM",
  "SN",
  "SO",
  "SR",
  "SS",
  "ST",
  "SV",
  "SX",
  "SY",
  "SZ",
  "TC",
  "TD",
  "TF",
  "TG",
  "TH",
  "TJ",
  "TK",
  "TL",
  "TM",
  "TN",
  "TO",
  "TR",
  "TT",
  "TV",
  "TW",
  "TZ",
  "UA",
  "UG",
  "UM",
  "US",
  "UY",
  "UZ",
  "VA",
  "VC",
  "VE",
  "VG",
  "VI",
  "VN",
  "VU",
  "WF",
  "WS",
  "YE",
  "YT",
  "ZA",
  "ZM",
  "ZW",
] as const;

function displayName(type: "currency" | "region", code: string): string {
  try {
    return new Intl.DisplayNames(["en"], { type }).of(code) ?? code;
  } catch {
    return code;
  }
}

function currencySymbol(code: string): string {
  try {
    return (
      new Intl.NumberFormat("en", {
        style: "currency",
        currency: code,
        currencyDisplay: "narrowSymbol",
      })
        .formatToParts(0)
        .find((part) => part.type === "currency")?.value ?? code
    );
  } catch {
    return code;
  }
}

function supportedCurrencyCodes(): string[] {
  const values = (Intl as unknown as IntlWithSupportedValues).supportedValuesOf?.("currency");
  const parsed = z.array(z.string().regex(/^[A-Z]{3}$/)).safeParse(values);
  return Array.from(
    new Set([...(parsed.success ? parsed.data : []), ...FALLBACK_CURRENCY_CODES]),
  ).sort();
}

export function defaultWorkspaceOptions(kind: WorkspaceOptionKind): WorkspaceOption[] {
  if (kind === "address-book" || kind === "supplier-product-type") return [];
  const codes = kind === "currency" ? supportedCurrencyCodes() : [...COUNTRY_CODES];
  return codes.map((code, sortIndex) => ({
    id: `${kind}:${code}`,
    kind,
    code,
    name: displayName(kind === "currency" ? "currency" : "region", code),
    symbol: kind === "currency" ? currencySymbol(code) : null,
    isFavorite: false,
    sortIndex,
  }));
}

export function normalizeWorkspaceOptions(
  kind: WorkspaceOptionKind,
  value: unknown,
): WorkspaceOption[] {
  const parsed = workspaceOptionListSchema.safeParse(value);
  if (!parsed.success || parsed.data.length === 0) return defaultWorkspaceOptions(kind);

  return parsed.data
    .filter((option) => option.kind === kind)
    .sort((left, right) => left.sortIndex - right.sortIndex)
    .map((option, sortIndex) => ({ ...option, sortIndex }));
}
